services:
  
  server:
    build:
      dockerfile: Dockerfile
      context: "./server"
    ports:
      - "5000:5000"

  client:
    build:
      dockerfile: Dockerfile
      context: "./client"
    ports:
      - "3000:3000"